# hostname (and path) to the root eg. http://spf13.com/
baseurl = "http://www.enten.fr/steven/"

# Site title
title = "enten.fr"

copyright = "(c) 2015 Steven Enten"

# Language
languageCode = "fr-FR"

# "yaml", "toml", "json"
metaDataFormat = "yaml"

# theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"

# pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "enten"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"


#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    brand = "steven.paris"
    topline = "code by Steven Enten"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"


    # Google Analytics.
    googleAnalytics = "Your Google Analytics tracking code"

    # Sidebar social links.
    github = "enten" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid
    rss = true  # switch to true to enable RSS icon link

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []
